server:
  servlet:
    context-path: /
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 40s
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/service-product/**
          filters:
            - RewritePath=/service-product/(?<remaining>.*), /${remaining}
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/service-user/**
          filters:
            - RewritePath=/service-user/(?<remaining>.*), /${remaining}
        - id: service-file
          uri: lb://file-service/**
          predicates:
            - Path=/file-service/**

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /service-product/v3/api-docs
        name: Service Product
      - url: /service-user/v3/api-docs
        name: Service User

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost